# Path related.
path_dataset: data/raw/brain_tumor_dataset.csv
path_raw_dataset: data/interim/raw_dataset.pkl
path_clean_dataset: data/processed/processed_dataset.pkl
path_train_set:
- data/interim/X_train.pkl
- data/interim/y_train.pkl
path_test_set:
- data/interim/X_test.pkl
- data/interim/y_test.pkl
path_train_num:
- data/interim/X_train_num.pkl
path_train_cat:
- data/interim/X_train_cat.pkl
path_set_final:
- data/interim/X_train_final.pkl
- data/interim/X_test_final.pkl

# Columns by data type related.
identifier_column:
- Patient_ID
int64_columns:
- Age
float64_columns:
- Tumor_Size
- Survival_Rate
- Tumor_Growth_Rate
object_columns:
- Gender
- Location
- Histology
- Stage
- Symptom_1
- Symptom_2
- Symptom_3
- Radiation_Treatment
- Surgery_Performed
- Chemotherapy
- Family_History
- MRI_Result
- Follow_Up_Required

# Predictors and label related.
label: Tumor_Type

# Debug and logging related.
print_debug: True